### ISSUE TITLE
When mod.postimage.org is down it takes forever to Reply or create New message

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#109]
Sat Mar 26 23:31:27 EDT 2016
ey@ey-home1:~$ telnet mod.postimage.org 80
Trying 46.229.166.178...

^C
It takes approximately 1 minute 30 seconds for http://vipvip.ca/ to show bottom frame when I hit Reply or New thread.

During that time tcpdump shows that I am trying to connect to mod.postimage.org over TCP port 80:
23:36:54.778219 IP 10.0.0.100.52591 > 46.229.166.178.80: Flags [S], seq 318325841, win 29200, options [mss 1460,sackOK,TS val 1063556 ecr 0,nop,wscale 7], length 0

**Comment by iamranger** [comment]
THANK YOU! I was going apeshit trying to figure out what was wrong. 

## 

Sent from myMail app for Android Saturday, 26 March 2016, 08:35PM -07:00 from BGmot < notifications@github.com> :

**Comment by BGmot** [comment]
Always welcome -)))
You should have posted a message at the forum I'd noticed earlier. I very rarely click Reply or New post ;-)

**Comment by iamranger** [comment]
Fixed: https://github.com/wolfpet/kitchen/commit/e63027943348a7c7a0ac8f14948315403e38ed87

**Comment by iamranger** [comment]
P.S. I did not notice it on the forum but in my own sandbox where I was working on something entirely else. So, I naturally assumed _I_ messed something up.
