### ISSUE TITLE
Cannot login into mobile interface if login has russian letters (and spaces)

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#116]
To reproduce - try logging in into http://vipvip.ca/mobile/index.html
Not sure if it is caused by russian letters or space in login though.

**Comment by iamranger** [comment]
will take a look

**Comment by iamranger** [comment]
This was actually a phantom error - the login were succeeding, but the app reported the error, because the login check was performed before the login was completed.

 Fixed

P.S. the script now also sets mainURL dynamically, no need to hardcode it.
