### ISSUE TITLE
ENH. New Profile Settings

### ISSUE THREAD

**Issue by wolfpet** [wolfpet/kitchen#123]
- [x] Mock-up
- [x] Style cleanup
- [x] Tabbed window
- [x] Color Chooser
- [ ] Notification settings

**Comment by wolfpet** [comment]
Adding the color chooser

**Comment by iamranger** [comment]
Way to go!

**Comment by wolfpet** [comment]
The best way to implement news feed/notifications is by rendering an overlay similar to facebook.  The old frameset is getting in a way, so I'll investigate the possibility of moving away from it first. So the last one is effectively on hold for now.
