### ISSUE TITLE
reply e-mail notification does not seem to work

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#141]

**Comment by BGmot** [comment]
Code is ok as I tested this on my server and it works. Apparently MTA is misconfigured at vipvip.ca.

**Comment by iamranger** [comment]
Verified - Works as designed.

**Comment by iamranger** [comment]
Stopped working after moving to the new server instance

**Comment by iamranger** [comment]
Fixed. GMail is now supported (requires PHPMailer)
