### ISSUE TITLE
Impossible to change e-mail in user's profile

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#142]
Always getting 'Profile Settings: Email does not match' despite entering the same new e-mail address in both 'Email' and 'Retype email' fields.

**Comment by iamranger** [comment]
Thank you for reporting it!

I will look into it

**Comment by BGmot** [comment]
I thought I fixed that in https://github.com/wolfpet/kitchen/pull/143

**Comment by iamranger** [comment]
your change has been merged and deployed to the website.
