### ISSUE TITLE
BUG: New PM popup is not always shown

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#19]
The reason is that `confa_sessions.updated` value is updated by many pages, including the ones that do not show the PM dialog (e.g. send.php, index.php), so, occasionally, by the time we check whether PM dialog is needed, that value may have already been updated. 

We need a separate column ("last_pm"?) in `confa_users` to store the ID of the last PM the user were notified about.

Do not use cookies, as this will make popup show on different devices multiple times for the same pmail.

**Comment by wolfpet** [comment]
hmmm how interesting!

**Comment by iamranger** [comment]
Yeah, took me a while to figure out what exactly is happening :)

**Comment by iamranger** [comment]
Added last_pm_check_time column to confa_users. It will be used instead of confa_sessions.updated
