### ISSUE TITLE
.gitignore and .sql files

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#26]
Why *.sql files are ignored by git when there is a folder /sql ?
It's missing add_last_pm_check_time.sql with:
alter table confa_sessions add column last_pm_check_time timestamp null default '0000-00-00 00:00:00';

**Comment by iamranger** [comment]
I'll take a look, but uploading may wait till tomorrow.

## No internet at home.

Sent from myMail app for Android Wednesday, 08 July 2015, 04:42PM -07:00 from BGmot < notifications@github.com> :

**Comment by iamranger** [comment]
Removed *.sql from .gitignore

**Comment by iamranger** [comment]
added add_last_pm_check_time.sql

**Comment by wolfpet** [comment]
yay!

**Comment by iamranger** [comment]
fixed add_last_pm_check_time.sql, as BGMot's reverse-engineering was not correct :-P
