### ISSUE TITLE
UTF8 in database

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#28]
Do you guys have readable content in MySQL for Russian letters?
In my instance the username field is garbage in confa_users for Russian Nicknames - it is not shown properly when I do mysql>select

For example if I register user "тест" I get:
mysql> select username from confa_users where id=13;
+--------------------+
| username           |
+--------------------+
| Ñ‚ÐµÑÑ‚           |
+--------------------+

Although the user works perfectly well (can login and post). The same problem exists for confa_posts table.

**Comment by iamranger** [comment]
## It worked for me right out of the box (EasyPHP, Win 7). Check your DB settings may be?

Sent from myMail app for Android Thursday, 09 July 2015, 08:28PM -07:00 from BGmot < notifications@github.com> :

**Comment by BGmot** [comment]
Ok. Thanks. Just checking. I am testing on Ubuntu 14 (not a fan of MS Windows). Please don't close this this issue for a while (assign it to me?)

**Comment by wolfpet** [comment]
Just got the latest Ubuntu, installed LAMP on EC2 -- worked right out of the box

**Comment by BGmot** [comment]
Must be something with my MySQL instance, it's god know how many years old. Btw there is not database create confa2; in this repo. Probably you are creating DB with some options?

**Comment by BGmot** [comment]
Turns out my terminal settings were just wrong (nothing is wrong with MySQL). So if you use putty to connect to your server default charset it Latin1 (set in putty's settings Window->Translation->Character set translation).
With default setting you have:
mysql> select username from confa_users where id=1020;
+----------+
| username |
+----------+
| Ð¢ÐµÑÑ     |
+----------+
1 row in set (0.00 sec)

Now change it to UTF-8 and everything is good:
mysql> select username from confa_users where id=1020;
+----------+
| username |
+----------+
| Тест     |
+----------+
1 row in set (0.00 sec)
