### ISSUE TITLE
BUG: Duplicate submissions are allowed in Private mail

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#29]
сообщения легко дублируются, сколько кликнешь на Send столько и сообщений придет.

**Comment by BGmot** [comment]
When you click on Send you are redirected on 'Confirmation' page, how do you click Send multiple times?

**Comment by iamranger** [comment]
I assume that when you're on a slow connection (read: mobile) it is quite possible to tap Send twice before confirmation page is displayed. 

The regular forum message form has a safeguard for this (a unique hidden field that is sent with the form) - the private message form could use it too. Alternatively, we could simply disable Send button when it is pressed, but this would leave the user with no means of repeating the submission in case of network failure (again, thinking mobile)

**Comment by iamranger** [comment]
Fixed
