### ISSUE TITLE
ENH: Users should be able to see edit history 

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#35]
Well, the next step is to implement versioning for message changes, so users can make changes at any time but still be accountable. I little bit more of UI work than basic implementation _and_ it requires changes to the database, but still is a fairly simple project.
1. Create new table confa_edits (?) with FK to confa_posts plus all the columns updated while editing (see post.php).
2. Add 'modified' column to confa_posts, type is datetime, defaults to null. 
3. Alter post.php to insert a new row to confa_edits with old content before updating confa_posts with the new one: either always (easiest), or there could be some grace period when the changes are not versioned (e.g. the message is not too old + no responses). Also, update 'modified' column, not 'created'
4. Alter can_edit_post() condition to remove obsolete constraints

UI changes:
1. Existing pages are to display 'modified' date when set with a marker (TBD) that message has been edited.
2. Message view (msg.php) to display "Message modified" marker (TBD) and a (possibly, hideable - the same way **BB Code Help** works) list of links to previous versions with dates. A click on such link will display the previous version of the message using the same interface as for the regular messages.
3. (Bonus) We could get _real_ fancy and use something like http://ejohn.org/projects/javascript-diff-algorithm/ to display the _differences_ between the versions.

**Comment by iamranger** [comment]
Do nothing, if new content matches the old. Do NOT create a new version.

**Comment by iamranger** [comment]
Items 1-3 and UI item 1 are done:

https://github.com/wolfpet/kitchen/commit/086b2320fc03330988bd17cfe86898501222c08e

**Comment by BGmot** [comment]
Item 4: please take a look at https://github.com/BGmot/kitchen/commit/62d4bb527096c800c6aad9e02a389c84dc7dd1e4 , not sure if you meant this to be that simple.

**Comment by iamranger** [comment]
Yeah, only I kept the 24 hrs check just in case. Revision history browser to complete this feature: https://github.com/wolfpet/kitchen/commit/31136cf462d0b32a1a908a46ec0d3a35ddfacc6e

There were also a couple of minor bug fixes since this commit. I decided not to implement a diff (UI #3) for now. Let's see how the clients accept it first ;)

**Comment by iamranger** [comment]
Remaining is the support for moderator tasks for versions: censor/delete. Currently, modcensor.php only supports censoring messages.

Links for these tasks are generated by ver.php

**Comment by iamranger** [comment]
A diff can be implemented the following way: subjects - via diffStrings in revisions list, bodies: via diffString() original\* bodies (as they are in database) in ver.php

**Comment by iamranger** [comment]
Closing, will create separate Issues for outstanding tasks
