### ISSUE TITLE
NEW: Implement message editing

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#4]
Add link Edit to the existing message available only to author of the message. 

Click loads standard "create new message" page but with current subject and body loaded for editing. Post action (post.php) updates the existing row in table.

Options:

1) Time-limited access to the feature e.g. 5 minutes after the message was posted
2) Editing is always available. versions are saved in a separate table and history of changes are available as links (e.g. below the message) listing date/time of the change. Click displays the change in bottom frame as usual message sans links at the bottom.

**Comment by iamranger** [comment]
Bumped up the priority.

Another (better?) option : the message can be edited by the author, until it has responses.

**Comment by BGmot** [comment]
Fid somebody request this feature? We can take the easiest approach at first: edit as many times as you want without any history. If people complain then we'll enhance the feature the way people want to see it.

**Comment by iamranger** [comment]
## Yes, it was requested and, in fact, it is very easy to implement. I have the code in svn on my local machine (I implemented it before we had github), just need to merge it and update the canEdit condition.

Sent from myMail app for Android Wednesday, 15 July 2015, 09:40PM -07:00 from BGmot < notifications@github.com> :

**Comment by iamranger** [comment]
Done. Feel free to take a look.

https://github.com/wolfpet/kitchen/commit/2dc28c2686fc8a581d888e5ab5a5b4dbe727e9d8

**Comment by BGmot** [comment]
It's working -)

**Comment by iamranger** [comment]
Glad to hear that. I'll create a new Issue/Enhancement for Editing history
