### ISSUE TITLE
NEW: Implement an option to forward private mail to email or SMS

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#5]
Possible approach: 

1) if the recipient has an email address filled in the profile, the forum will automatically forward a copy of PM to that address.

2) SMS option needs investigation

**Comment by BGmot** [comment]
I guess sending to e-mail is already implemented and I don't think it is feasible to send SMS, it's easier to implement sending to facebook or ICQ or any other IM (you name it).

**Comment by iamranger** [comment]
The legacy implementation only sends a notification to email, not the content. I did not test this feature at all, so it may not work at all.

Integration with a messenger may be an interesting option to explore.

**Comment by BGmot** [comment]
Notification works.
To add PM body to the notification e-mail please accept https://github.com/wolfpet/kitchen/pull/90 .

**Comment by iamranger** [comment]
Change  accepted and deployed. Closing.
