### ISSUE TITLE
NEW: Twitter support

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#50]
Basically, idea is to make sharing of twitter links easier. A link (e.g. https://twitter.com/elonmusk/status/627040381729906688) is to be turned into embeddable code when the content is saved, similar to youtube/rutube, but the source link can be restored back to its original form if needed, e.g. for editing.

To reiterate:
1. As save, the code will call Twitter's oEmbed API so the link becomes [embed src=<link> type=twitter]<content returned by oEmbed API>[/embed]
2. At edit, the code will translate [embed] tag back to <link>
3. At display, [embed] tag is translated simply into <content>.
4. type attribute can be used to check whether to display a "movie clip" icon for youtube etc

Considerations:
1. User-entered [embed] tags should not be allowed (e.g. removed at save)

Youtube/rutube support should be similarly re-factored.

**Comment by iamranger** [comment]
Implemented as part of "before_bbcode". 

NOT an ideal solution, as we make calls to twitter API every time the message is to be displayed, if there are complaints, we'll have to refactor the whole thing as described above.

**Comment by wolfpet** [comment]
Very nice
