### ISSUE TITLE
HELP! Steps to enable mbstrings PHP extensions needed

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#51]
If you have Linux, could you complete and then document the steps required to enable _mbstring_ extension?

http://php.net/manual/en/mbstring.installation.php

This extension is required for highlighting of the changes between revisions. The code change itself has been implemented and tested, but never deployed to 'production'-like environment.

**Comment by BGmot** [comment]
They say you need to recompile php. It's doable but I wonder whether we really need it - I am looking at my dev server looks like mbstring is already working as expected.
![screenshot - edit with mbstring](https://cloud.githubusercontent.com/assets/1423807/9347033/3d4711d2-45f2-11e5-8851-f936cc8e8e8e.png)

**Comment by afiglee** [comment]
Does not work. Recompiled with --enable-mbstring.
As before, no results. phpinfo says (Zend multibyte support disabled).
Any hints?

**Comment by BGmot** [comment]
_edited_
Compare all versions with phinfo() at http://kitchen.bgmot.com/test.php where this feature working maybe?

**Comment by BGmot** [comment]
What's your php and apache version? I can try...

**Comment by iamranger** [comment]
## Try info.php on kirdyk.radier.ca

Sent from myMail app for Android Wednesday, 26 August 2015, 10:06AM -07:00 from BGmot < notifications@github.com> :

**Comment by afiglee** [comment]
Hmm.. Just ran command line:
sapi/cli/php -d zend.multibyte=1 -i | grep -i multibyte
Configure Command =>  './configure'  '--with-zlib' '--with-bz2' '--with-curl' '--enable-exif' '--with-mysql' '--with-mysqli' '--with-openssl' '--enable-shmop' '--enable-sockets' '--enable-zip' '--with-readline' '--with-pdo-mysql' '--enable-opcache' '--with-mhash' '--enable-calendar' '--enable-ftp' '--with-gettext' '--with-gmp' '--enable-pcntl' '--enable-mbstring' '--enable-zend-multibyte'
Zend Multibyte Support => provided by mbstring
zend.multibyte => On => On
Multibyte Support => enabled
Multibyte string engine => libmbfl
Multibyte (japanese) regex support => enabled
Multibyte regex (oniguruma) backtrack check => On
Multibyte regex (oniguruma) version => 5.9.2

Seems like php.ini problem? Suspicious is zend.script_encoding

**Comment by BGmot** [comment]
# php -i | grep -i multibyte
Zend Multibyte Support => provided by mbstring
zend.multibyte => Off => Off
Multibyte Support => enabled
Multibyte string engine => libmbfl
Multibyte (japanese) regex support => enabled
Multibyte regex (oniguruma) backtrack check => On
Multibyte regex (oniguruma) version => 5.9.2

I don't think it is php.ini problem.
In my php I have
;zend.multibyte = Off

Will try to dig into this later.

**Comment by BGmot** [comment]
Ok. Your test with sapi/cli/php is just showing that you compiled php-cli with mbstring support, I can't say whether you compiled libphp5.so, it is what really used by apache.
Here is how I would approach this jsut to test (without destroying/removing/modifying current php module for apache). I don't know what Linux flavor you are running so these are instructions for Ubuntu.

```
- You are in some folder as local user (not root)
- Prepare dev environment
sudo apt-get install build-essential libxml2-dev apache2-dev

- Download your version of php
wget -O php-5.5.28.tar.bz2 http://ca1.php.net/get/php-5.5.28.tar.bz2/from/this/mirror

- Check md5
md5sum php-5.5.28.tar.bz2
5595dffa11f153e5b5cb8bf57242797e  php-5.5.28.tar.bz2

bunzip2 php-5.5.28.tar.bz2
tar -xf php-5.5.28.tar
cd php-5.5.28/

- Make sure that /usr/bin/apxs exists, if dev packages installed properly then it should exist
./configure --with-apxs2=/usr/bin/apxs --enable-mbstring
make
- drink beer here, it'll take some time

- Check that the module library has been generated and it is readable by all (actually only user that runs apache need access)
ls -l libs/libphp5.so

- move it to some place definitely accessible by the user that runs apache
cp libs/libphp5.so /tmp

- back up your current php-mod config
cp /etc/apache2/mods-available/php5.load ~

- now make apache use our just compiled module
sudo vim /etc/apache2/mods-available/php5.load
- change this single line to point to our .so file:
LoadModule php5_module /tmp/libphp5.so

sudo /etc/init.d/apache2 restart

- test with phpinfo() -> mbstring should be there.

--- rollback
sudo cp ~/php5.load /etc/apache2/mods-available/
sudo /etc/init.d/apache2 restart
```

------------------ Test it on dev server first.
My only concern is I don't know how to see what php extension is currently compiled into your php module and which one is loaded dynamically. So after making the change above you may end up with less modules loaded, it may or may not affect the website.

**Comment by iamranger** [comment]
## Wow... Nice job!!

Sent from myMail app for Android Wednesday, 26 August 2015, 06:26PM -07:00 from BGmot < notifications@github.com> :

**Comment by BGmot** [comment]
Весело тут у вас -))) mbstring починили, всё остальное нафик слетело? -)

**Comment by afiglee** [comment]
Токмо phalcon  и слетел. Я его пробовал с утра ставить, не шевелится. Ranger как то без рута ставил.. Нипанятно..

**Comment by BGmot** [comment]
без рута phalcon нельзя поставить, может у него sudo есть?
а чего эт он слетел? он внешний модуль...

**Comment by afiglee** [comment]
Понятия не имею.
Вот выдало результаты утром:

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/lib64/php/modules/
Installing header files:          /usr/include/php/

Thanks for compiling Phalcon!
Build succeed: Please restart your web server to complete the installation
[root@web1 build]# make test
make: **\* No rule to make target `test'.  Stop.
[root@web1 build]# /sbin/service httpd restart
Stopping httpd:                                            [  OK  ]
Starting httpd: [Thu Aug 27 10:29:29 2015] [warn] module php5_module is already loaded, skipping
httpd: Could not reliably determine the server's fully qualified domain name, using web1.radier.ca for ServerName
                                                           [  OK  ]

**Comment by BGmot** [comment]
Такое есть?
$ cat /etc/php5/apache2/conf.d/30-phalcon.ini
; configuration for php phalcon module
; priority=30
extension=phalcon.so

**Comment by afiglee** [comment]
Есть такое:
$ cat /etc/php.d/phalcon.ini 
extension=phalcon.so

В апачи конфигах никаких "extension" нет

**Comment by BGmot** [comment]
В апачи его и не должно быть (другой механизм загрузки), смотрю я на http://kirdyk.radier.ca/info.php и похоже он теперь берёт конфигурацию из другого места:
Configuration File (php.ini) Path = /usr/local/lib 
А старый должен был брать откуда-нибудь из /etc/php5/apache2 или где там старый php.ini лежит для apache? тот в свою очередь должен обрабатывать твой /etc/php.d/ фолдер и загружать phalcon.
Чтобы заставить вновь скомпилированный php модуль смотреть на старый конфиг, думаю, надо его перекомпилировать с опцией 
--with-config-file-path=<путь к старому php.ini> 
или же создать php.ini в /usr/local/lib (похоже он там просто отсутствует)

**Comment by afiglee** [comment]
Создал линк к /etc/php.ini и /etc/php.d в /usr/local/lib, рестартнул. Безрезультатно.
Я конечно могу перекомпилить с with-config-path, но боюсь как бы вообще все не отвалилось.
Времени особо разбиратся нет. А тут надо разобратся, наобум можно долго вокруг да около ходить

**Comment by afiglee** [comment]
Ладно, оставим все как есть до наличия точных инструкций. Некогда этим заниматся

**Comment by BGmot** [comment]
/usr/local/lib/php.ini  появился в phpinfo(), теперь отсутсвтует "Scan this dir for additional .ini files"
Единственное, что могу предложить без перекомпиляции 

```
PHP_INI_SCAN_DIR="/etc/php.d/"
export PHP_INI_SCAN_DIR
и рестарт апачи
```

А по-хорошему надо перекомпилировать с --with-config-file-path=/etc/php.ini --with-config-file-scan-dir=/etc/php.d и тогда должно взлететь без танцев с бубном.
Извиняюсь за косяки, надо пробовать на тест машине -(((
Read-only access дать можешь? а то так год можно траблешутить -)

**Comment by BGmot** [comment]
упс... пропустил "оставим всё как есть" пока писал сообщение.
Точные инструкции можно дать, когда есть такая же тест машина, а на моей dev и так всё без перекомпиляции работает -(((
Ок.

**Comment by afiglee** [comment]
Thank you. Recompiling with config seems worked. "Seems"

**Comment by BGmot** [comment]
Now looks like /etc/php.ini is missing, is it there? Not critical but still not nice.
Plus I noticed you had this error when apache started:

```
Starting httpd: [Thu Aug 27 10:29:29 2015] [warn] module php5_module is already loaded, skipping
```

Obviously you are trying to load this module twice. I'd suggest to do this on your apache folder to find out where:

```
grep -r libphp5.so /etc/apache2/
```

You should see at least two lines with LoadModule, remove one of them.
Cheers!

**Comment by afiglee** [comment]
Thank you, I noticed that. There is php.ini.  In every place. I know about twice module loading. I do not have an idea to spend rest of my life improving that server. It works, let it be. I did not want to touch it at all in the first place.

**Comment by BGmot** [comment]
got it.

**Comment by iamranger** [comment]
Thanks a lot! I'll close the ticket.
