### ISSUE TITLE
BUG: Revisions link is displayed when there are no revisions

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#60]
Users are allowed to update their messages without creating a revision in some cases: shortly after it was submitted, and when there were no responses yet.

Currently, Revisions link is displayed when the message was modified. It needs to be displayed only when there _are_ revisions

**Comment by wolfpet** [comment]
ahhh now this explains it! ;-)

**Comment by iamranger** [comment]
OK, I lied. The code is correct, and the problem is (_again_!) in mbstring extension not loaded. 

I added the condition to handle this more gracefully: the revisions will be displayed albeit without highlighting of the differences.
