### ISSUE TITLE
BUG  clicking on Profile link gives an error

### ISSUE THREAD

**Issue by wolfpet** [wolfpet/kitchen#72]
The issue is with safe_mode field missing in confa_users and there is no sql script that currently adds it.

must add
ALTER TABLE confa_users ADD COLUMN safe_mode SMALLINT NULL DEFAULT 0;

**Comment by iamranger** [comment]
BS! :)

https://github.com/wolfpet/kitchen/blob/master/Forum/sql/add_safe_mode.sql

**Comment by iamranger** [comment]
by design, the column is only required in confa_sessions table. must be some leftovers after the refactoring.

I'll take a look

**Comment by wolfpet** [comment]
Gotcha!  Well, I'm planning to open a playground forum at test.vipvip.ca; you are welcome to try a new deployment. Should be easy to reproduce.

**Comment by iamranger** [comment]
Just had to remove this name from the SQL statement in profile.php. The new version is on git.

**Comment by wolfpet** [comment]
thx!
