### ISSUE TITLE
ENH: Make reputation changes asynchronously

### ISSUE THREAD

**Issue by iamranger** [wolfpet/kitchen#85]
Rationale: page reload screws up the video playback

Low priority.

**Comment by wolfpet** [comment]
haha I was thinking about it the other day.  The code exists in the Mobile project, just copy and paste ;-)

**Comment by iamranger** [comment]
Will do. Copy-paste is strong with this one.

**Comment by iamranger** [comment]
https://github.com/wolfpet/kitchen/commit/d36f181c86c5c44c7c5fe7a0f27918c436f9efb9
