### ISSUE TITLE
Happy New Year ?

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#89]
I think it would be nice to add a little of charm to the forum as we are counting down days/hours until the New Year. I propose to create a branch with a little banner so you can easily switch it on and off, like this one https://github.com/BGmot/kitchen/tree/ny_2016 
![image](https://cloud.githubusercontent.com/assets/1423807/12005271/f56d524e-ab69-11e5-91e5-feae5e69cc66.png)

**Comment by iamranger** [comment]
Sure, I was gonna externalize banner, forum title and other forum-specific data anyway - then it will be easy to add this stuff without editing actual PHP pages.
