### ISSUE TITLE
Warning: Missing argument 2 for before_bbcode()

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#91]
I am getting following error in the bottom frame:
Warning: Missing argument 2 for before_bbcode(), called in /var/www/kitchen/Forum/php/bbcode.php on line 230 and defined in /var/www/kitchen/Forum/php/bbcode.php on line 109

And indeed we are calling before_bbcode() with one argument while it is defined with two:
https://github.com/wolfpet/kitchen/blob/master/Forum/php/bbcode.php#L109
https://github.com/wolfpet/kitchen/blob/master/Forum/php/bbcode.php#L230

Anybody has an idea what's the point of having $has_video?

**Comment by iamranger** [comment]
## It's fine - that parameter is optional, and is used in post.php. You can (and should) turn off php warnings in settings.php 

Sent from myMail app for Android Sunday, 27 December 2015, 07:40PM -08:00 from BGmot < notifications@github.com> :

**Comment by BGmot** [comment]
I love having warnings on on a dev server and no warnings displayed -)))
This warning will disappear if you merge https://github.com/wolfpet/kitchen/pull/92 (quickly tested does not seem to affect functionality in any way.

**Comment by iamranger** [comment]
Merged
