### ISSUE TITLE
Admin links for non-admin users

### ISSUE THREAD

**Issue by BGmot** [wolfpet/kitchen#95]
I am not an admin but when I click on Bookmarks I see links that should be visible only to admins

**Comment by iamranger** [comment]
Hmmm... I can't seem to reproduce this one. Could you tell which links are visible to you?

**Comment by BGmot** [comment]
![img_20160204_073039](https://cloud.githubusercontent.com/assets/1423807/12815012/6ca658ee-cb11-11e5-909d-88847f65b895.png)

**Comment by iamranger** [comment]
## Confirmed. 

Sent from myMail app for Android Thursday, 04 February 2016, 04:32AM -08:00 from BGmot < notifications@github.com> :

**Comment by iamranger** [comment]
## mybookmarks.php is overwriting a global variable. Easy fix 

Sent from myMail app for Android Thursday, 04 February 2016, 04:32AM -08:00 from BGmot < notifications@github.com> :

**Comment by iamranger** [comment]
Fixed in trunk & on vipvip.ca

**Comment by iamranger** [comment]
https://github.com/wolfpet/kitchen/commit/3bc3d9eade473f2289eb7f267bde18e0eebd2d1d
